version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/softcode.se
    container_name: softcode-web

  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: ["composer"]
